# Generated by Django 5.1.6 on 2025-02-12 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('card_subtitle', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=400)),
                ('card_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardgame.cardset')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(default=0)),
                ('collected_cards', models.ManyToManyField(to='cardgame.card')),
            ],
        ),
    ]
