# Generated by Django 5.1.6 on 2025-02-18 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('card_set_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('card_set_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('card_subtitle', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=400)),
                ('card_created_at', models.DateTimeField(auto_now_add=True)),
                ('card_image_link', models.ImageField(default='static/card_images/do_not_remove.png', upload_to='static/card_images')),
                ('card_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardgame.cardset')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('points_reward', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='upcoming', max_length=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='cardgame.card')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cardgame.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_profile_points', models.IntegerField(default=0)),
                ('user_profile_collected_cards', models.ManyToManyField(to='cardgame.card')),
            ],
        ),
    ]
