# Generated by Django 5.1.6 on 2025-02-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardset',
            old_name='description',
            new_name='card_set_description',
        ),
        migrations.RenameField(
            model_name='cardset',
            old_name='name',
            new_name='card_set_name',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardgame.cardset'),
        ),
    ]
