# Generated by Django 5.1.6 on 2025-02-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_rename_description_cardset_card_set_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='collected_cards',
            new_name='user_profile_collected_cards',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='points',
            new_name='user_profile_points',
        ),
    ]
