# Generated by Django 5.1.6 on 2025-02-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_rename_collected_cards_userprofile_user_profile_collected_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('Card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardgame.card')),
            ],
        ),
    ]
