# Generated by Django 5.1.6 on 2025-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image_link',
            field=models.ImageField(default='card_images/do_not_remove.png', upload_to='card_images'),
        ),
    ]
