# Generated by Django 5.1.6 on 2025-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0011_alter_card_card_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image_link',
            field=models.ImageField(default='cardgame/media/card_images/do_not_remove.png', upload_to='cardgame/media/card_images'),
        ),
    ]
